const types = {
   FETCH_PRODUCTS: 'FETCH_PRODUCTS',
   ADD_PRODUCT: 'ADD_PRODUCT',
   DELETE_PRODUCT: 'DELETE_PRODUCT',
   EDIT_PRODUCT: 'EDIT_PRODUCT',
   SAVE_PRODUCT: 'SAVE_PRODUCT',
   CHANGE_PRODUCT_STATUS: 'CHANGE_PRODUCT_STATUS'
}

export default types
